# Generated by Django 5.2.7 on 2025-10-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
