# Generated by Django 5.2.7 on 2026-01-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_contact',
            field=models.CharField(max_length=15),
        ),
    ]
