# Generated by Django 5.2.7 on 2026-01-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_userprofile_phone_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
