# Generated by Django 5.2.7 on 2025-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('reader_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_contact', models.CharField(max_length=15, unique=True)),
                ('reader_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
