# Generated by Django 5.2.7 on 2026-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Admin'), ('accepted', 'Accepted'), ('returned', 'Returned')], default='waiting', max_length=10),
        ),
    ]
