# Generated by Django 5.2.7 on 2026-02-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_remove_order_confirmed_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Admin'), ('accepted', 'Accepted'), ('returned', 'Returned'), ('refused', 'Refused')], default='waiting', max_length=10),
        ),
    ]
