# Generated by Django 5.2.7 on 2025-11-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_user_delete_reader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User_address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_name',
            new_name='user_name',
        ),
    ]
