# Generated by Django 5.2.7 on 2026-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='feedback',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
