# Generated by Django 5.2.7 on 2026-02-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
